name: Build Electron App for Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build TypeScript and copy index.html
        run: npm run build

      - name: Package Electron app (no publishing)
        run: npm run package

      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: dist/*.AppImage

      - name: Upload Linux .deb package
        uses: actions/upload-artifact@v4
        with:
          name: linux-deb
          path: dist/*.deb
